"""SUMO network import and labelled synthetic demand for Stage 5.

Observed Chennai counts/OD matrices were not found in the public no-key
sources used here. Demand is therefore SYNTHETIC. SUMO output is simulated
traffic, not live Chennai observations.
"""

from __future__ import annotations

import os
import shutil
import subprocess
import xml.etree.ElementTree as ET
from dataclasses import asdict, dataclass
from datetime import datetime, timezone
from pathlib import Path

SUMO_HOME_CANDIDATES = (
    os.environ.get("SUMO_HOME", ""),
    "/usr/share/sumo",
    "/usr/local/share/sumo",
)
SYNTHETIC_SEED = 8597
VEHICLE_TYPE_CLASS = "SCENARIO"
SCENARIO_DEFAULT_SPEED_KPH = 30.0
SCENARIO_DEFAULT_LANES = 1


@dataclass(frozen=True)
class TrafficFeasibilityReport:
    """What public Chennai traffic observations were and were not found."""

    retrieved_at_utc: str
    observed_link_counts: str
    observed_od_matrix: str
    observed_travel_times: str
    observed_speeds: str
    vehicle_composition: str
    incident_records: str
    demand_class: str
    calibration_class: str
    notes: str


@dataclass(frozen=True)
class SumoConversionReport:
    """Losses from converting the Stage 3 OSM extract into a SUMO network."""

    osm_pbf_path: str
    net_path: str
    netconvert_version: str
    osm_arc_count: int | None
    sumo_edge_count: int
    sumo_lane_count: int
    sumo_junction_count: int
    warning_count: int
    error_count: int
    discarded_note: str


def _utc_now() -> str:
    return datetime.now(timezone.utc).isoformat()


def require_netconvert() -> str:
    binary = shutil.which("netconvert")
    if binary is None:
        raise RuntimeError("netconvert is required for Stage 5 SUMO import.")
    completed = subprocess.run(
        [binary, "--version"],
        check=True,
        capture_output=True,
        text=True,
    )
    return (completed.stdout or completed.stderr).splitlines()[0].strip()


def sumo_home() -> Path:
    for candidate in SUMO_HOME_CANDIDATES:
        path = Path(candidate)
        if candidate and path.is_dir():
            return path
    raise RuntimeError("SUMO_HOME is not set and /usr/share/sumo was not found.")


def write_traffic_feasibility_report(path: Path) -> TrafficFeasibilityReport:
    """Record that independent Chennai counts were not obtained."""

    report = TrafficFeasibilityReport(
        retrieved_at_utc=_utc_now(),
        observed_link_counts="UNAVAILABLE",
        observed_od_matrix="UNAVAILABLE",
        observed_travel_times="UNAVAILABLE",
        observed_speeds="UNAVAILABLE",
        vehicle_composition="UNAVAILABLE as a calibrated Chennai mix; vehicle types below are scenario labels",
        incident_records="UNAVAILABLE as a timestamped public feed",
        demand_class="SYNTHETIC",
        calibration_class="SYNTHETIC",
        notes=(
            "No licence-compatible public Chennai link-count or OD matrix was "
            "acquired in this run. OpenCity flood/drain layers and OSM topology "
            "are not traffic counts. SUMO demand is generated by seeded random "
            "trips and must not be described as calibrated Chennai demand."
        ),
    )
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        __import__("json").dumps(asdict(report), indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )
    return report


def osm_xml_from_pbf(pbf_path: Path, osm_xml_path: Path) -> Path:
    """Convert a PBF extract to OSM XML so netconvert can read it."""

    osmium = shutil.which("osmium")
    if osmium is None:
        raise RuntimeError("osmium-tool is required to convert the clipped PBF to OSM XML.")
    osm_xml_path.parent.mkdir(parents=True, exist_ok=True)
    completed = subprocess.run(
        [osmium, "cat", "--overwrite", "-f", "osm", "-o", str(osm_xml_path), str(pbf_path)],
        check=False,
        capture_output=True,
        text=True,
    )
    if completed.returncode != 0 or not osm_xml_path.is_file():
        raise RuntimeError(
            "osmium cat failed to write OSM XML:\n"
            f"{completed.stderr or completed.stdout}"
        )
    return osm_xml_path


def convert_osm_pbf_to_sumo_net(
    osm_pbf: Path,
    output_net: Path,
    *,
    osm_arc_count: int | None = None,
) -> tuple[Path, SumoConversionReport, str]:
    """Import the GCC-clipped OSM extract with netconvert and count objects."""

    osm_xml = osm_pbf.with_suffix(".osm")
    osm_xml_from_pbf(osm_pbf, osm_xml)
    output_net.parent.mkdir(parents=True, exist_ok=True)
    version = require_netconvert()
    type_file = sumo_home() / "data" / "typemap" / "osmNetconvert.typ.xml"
    env = os.environ.copy()
    env.setdefault("SUMO_HOME", str(sumo_home()))
    command = [
        "netconvert",
        "--osm-files",
        str(osm_xml),
        "--output-file",
        str(output_net),
        "--geometry.remove",
        "true",
        "--ramps.guess",
        "true",
        "--junctions.join",
        "true",
        "--tls.guess-signals",
        "true",
        "--tls.discard-simple",
        "true",
        "--tls.join",
        "true",
        "--ignore-errors.edge-type",
        "true",
    ]
    if type_file.is_file():
        command.extend(["--type-files", str(type_file)])
    completed = subprocess.run(command, check=False, capture_output=True, text=True, env=env)
    log = (completed.stderr or "") + "\n" + (completed.stdout or "")
    if completed.returncode != 0 or not output_net.is_file():
        raise RuntimeError(f"netconvert failed:\n{log[-4000:]}")
    edge_count, lane_count, junction_count = _count_sumo_net(output_net)
    warning_count = log.lower().count("warning")
    error_count = sum(1 for line in log.splitlines() if line.lower().startswith("error"))
    report = SumoConversionReport(
        osm_pbf_path=str(osm_pbf),
        net_path=str(output_net),
        netconvert_version=version,
        osm_arc_count=osm_arc_count,
        sumo_edge_count=edge_count,
        sumo_lane_count=lane_count,
        sumo_junction_count=junction_count,
        warning_count=warning_count,
        error_count=error_count,
        discarded_note=(
            "netconvert rebuilds OSM ways into SUMO edges and junctions. "
            "Edge counts are not expected to equal Stage 3 directed OSM arcs. "
            "Turn restrictions and some service/access ways may be dropped or simplified."
        ),
    )
    return output_net, report, log


def _count_sumo_net(net_path: Path) -> tuple[int, int, int]:
    tree = ET.parse(net_path)
    root = tree.getroot()
    edges = [elem for elem in root.findall("edge") if elem.get("function") != "internal"]
    lanes = [lane for edge in edges for lane in edge.findall("lane")]
    return len(edges), len(lanes), len(root.findall("junction"))


@dataclass(frozen=True)
class GraphToSumoReport:
    """Stage 3 graph imported as SUMO node/edge files after OSM netconvert failed."""

    method: str
    netconvert_version: str
    node_count: int
    edge_count: int
    observed_speed_count: int
    scenario_speed_count: int
    scenario_speed_kph: float
    observed_lane_count: int
    scenario_lane_count: int
    sumo_edge_count: int
    sumo_lane_count: int
    sumo_junction_count: int
    osm_netconvert_status: str
    speed_policy: str


def _xml_escape(value: str) -> str:
    return (
        value.replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace('"', "&quot;")
    )


def _parse_positive_int(value: object) -> int | None:
    if value is None:
        return None
    text = str(value).strip()
    if text in {"", "nan", "None"}:
        return None
    try:
        number = int(float(text))
    except ValueError:
        return None
    return number if number > 0 else None


def write_plain_sumo_from_graphml(
    graphml_path: Path,
    nodes_path: Path,
    edges_path: Path,
) -> dict[str, int]:
    """Write SUMO plain node/edge XML from the Stage 3 GraphML."""

    import networkx as nx
    from pyproj import Transformer

    from chennai_routing.preprocessing.roads import parse_explicit_osm_maxspeed_kph

    graph = nx.read_graphml(graphml_path)
    transformer = Transformer.from_crs("EPSG:4326", "EPSG:32644", always_xy=True)
    nodes_path.parent.mkdir(parents=True, exist_ok=True)
    observed_speed = scenario_speed = observed_lanes = scenario_lanes = 0

    with nodes_path.open("w", encoding="utf-8") as handle:
        handle.write('<?xml version="1.0" encoding="UTF-8"?>\n<nodes>\n')
        for node_id, data in graph.nodes(data=True):
            try:
                lon = float(data["x"])
                lat = float(data["y"])
            except (KeyError, TypeError, ValueError):
                continue
            easting, northing = transformer.transform(lon, lat)
            handle.write(
                f'  <node id="{_xml_escape(str(node_id))}" x="{easting:.3f}" y="{northing:.3f}"/>\n'
            )
        handle.write("</nodes>\n")

    with edges_path.open("w", encoding="utf-8") as handle:
        handle.write('<?xml version="1.0" encoding="UTF-8"?>\n<edges>\n')
        for u, v, data in graph.edges(data=True):
            speed_kph = parse_explicit_osm_maxspeed_kph(data.get("maxspeed"))
            if speed_kph is None:
                speed_kph = SCENARIO_DEFAULT_SPEED_KPH
                scenario_speed += 1
            else:
                observed_speed += 1
            lanes = _parse_positive_int(data.get("lanes"))
            if lanes is None:
                lanes = SCENARIO_DEFAULT_LANES
                scenario_lanes += 1
            else:
                observed_lanes += 1
            edge_id = str(data.get("stage3_arc_id") or f"{u}_{v}")
            handle.write(
                "  <edge "
                f'id="{_xml_escape(edge_id)}" '
                f'from="{_xml_escape(str(u))}" '
                f'to="{_xml_escape(str(v))}" '
                f'numLanes="{lanes}" '
                f'speed="{speed_kph / 3.6:.4f}"/>\n'
            )
        handle.write("</edges>\n")
    return {
        "node_count": graph.number_of_nodes(),
        "edge_count": graph.number_of_edges(),
        "observed_speed_count": observed_speed,
        "scenario_speed_count": scenario_speed,
        "observed_lane_count": observed_lanes,
        "scenario_lane_count": scenario_lanes,
    }


def convert_graphml_to_sumo_net(
    graphml_path: Path,
    output_net: Path,
    *,
    osm_netconvert_status: str,
) -> tuple[Path, GraphToSumoReport]:
    """Import the Stage 3 graph as SUMO plain files, then netconvert."""

    output_net.parent.mkdir(parents=True, exist_ok=True)
    nodes_path = output_net.with_name("chennai_gcc_2022.nod.xml")
    edges_path = output_net.with_name("chennai_gcc_2022.edg.xml")
    counts = write_plain_sumo_from_graphml(graphml_path, nodes_path, edges_path)
    version = require_netconvert()
    env = os.environ.copy()
    env.setdefault("SUMO_HOME", str(sumo_home()))
    completed = subprocess.run(
        [
            "netconvert",
            "--node-files",
            str(nodes_path),
            "--edge-files",
            str(edges_path),
            "--output-file",
            str(output_net),
            "--ignore-errors",
            "true",
        ],
        check=False,
        capture_output=True,
        text=True,
        env=env,
    )
    log = (completed.stderr or "") + "\n" + (completed.stdout or "")
    (output_net.parent / "graph_netconvert.log").write_text(log, encoding="utf-8")
    if completed.returncode != 0 or not output_net.is_file():
        raise RuntimeError(f"SUMO node/edge netconvert failed:\n{log[-4000:]}")
    edge_count, lane_count, junction_count = _count_sumo_net(output_net)
    report = GraphToSumoReport(
        method="stage3_graphml_plain_node_edge",
        netconvert_version=version,
        node_count=counts["node_count"],
        edge_count=counts["edge_count"],
        observed_speed_count=counts["observed_speed_count"],
        scenario_speed_count=counts["scenario_speed_count"],
        scenario_speed_kph=SCENARIO_DEFAULT_SPEED_KPH,
        observed_lane_count=counts["observed_lane_count"],
        scenario_lane_count=counts["scenario_lane_count"],
        sumo_edge_count=edge_count,
        sumo_lane_count=lane_count,
        sumo_junction_count=junction_count,
        osm_netconvert_status=osm_netconvert_status,
        speed_policy=(
            "Explicit OSM maxspeed is used where parseable. Remaining arcs receive "
            f"a labelled SCENARIO default of {SCENARIO_DEFAULT_SPEED_KPH} km/h. "
            "Missing lanes receive a labelled SCENARIO default of "
            f"{SCENARIO_DEFAULT_LANES}."
        ),
    )
    return output_net, report


def write_scenario_vehicle_types(path: Path) -> Path:
    """Write labelled scenario vehicle types. These are not a Chennai mix."""

    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        """<?xml version="1.0" encoding="UTF-8"?>
<routes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <!-- SCENARIO labels only. Not a calibrated Chennai fleet mix. -->
  <vType id="passenger" vClass="passenger" accel="2.6" decel="4.5" sigma="0.5" length="5.0" maxSpeed="13.89"/>
  <vType id="two_wheeler" vClass="motorcycle" accel="3.0" decel="6.0" sigma="0.5" length="2.2" maxSpeed="13.89"/>
  <vType id="bus" vClass="bus" accel="1.2" decel="4.0" sigma="0.5" length="12.0" maxSpeed="11.11"/>
  <vType id="emergency" vClass="emergency" accel="2.6" decel="4.5" sigma="0.5" length="5.5" maxSpeed="16.67"/>
</routes>
""",
        encoding="utf-8",
    )
    return path


def write_synthetic_trips(
    net_path: Path,
    trips_path: Path,
    *,
    seed: int = SYNTHETIC_SEED,
    period_seconds: float = 5.0,
    end_seconds: int = 300,
) -> Path:
    """Generate seeded random trips. Demand class: SYNTHETIC."""

    trips_path.parent.mkdir(parents=True, exist_ok=True)
    tool = sumo_home() / "tools" / "randomTrips.py"
    if not tool.is_file():
        raise RuntimeError(f"SUMO randomTrips.py not found at {tool}")
    completed = subprocess.run(
        [
            "python3",
            str(tool),
            "-n",
            str(net_path),
            "-o",
            str(trips_path),
            "--seed",
            str(seed),
            "--period",
            str(period_seconds),
            "--end",
            str(end_seconds),
        ],
        check=False,
        capture_output=True,
        text=True,
    )
    if completed.returncode != 0 or not trips_path.is_file():
        raise RuntimeError(
            "randomTrips.py failed to write synthetic demand:\n"
            f"{completed.stderr or completed.stdout}"
        )
    return trips_path


def write_sumo_config(
    path: Path,
    *,
    net_file: Path,
    route_file: Path,
    additional_files: list[Path],
    seed: int = SYNTHETIC_SEED,
    end_seconds: int = 300,
) -> Path:
    """Write a deterministic SUMO configuration for the synthetic smoke scenario."""

    path.parent.mkdir(parents=True, exist_ok=True)
    extra = ",".join(str(item.name) for item in additional_files)
    additional_xml = f'        <additional-files value="{extra}"/>\n' if extra else ""
    path.write_text(
        f"""<?xml version="1.0" encoding="UTF-8"?>
<configuration>
    <input>
        <net-file value="{net_file.name}"/>
        <route-files value="{route_file.name}"/>
{additional_xml}    </input>
    <time>
        <begin value="0"/>
        <end value="{end_seconds}"/>
    </time>
    <random_number>
        <seed value="{seed}"/>
    </random_number>
    <processing>
        <ignore-route-errors value="true"/>
    </processing>
</configuration>
""",
        encoding="utf-8",
    )
    return path


def count_trip_elements(trips_path: Path) -> int:
    tree = ET.parse(trips_path)
    return len(tree.getroot().findall("trip"))
